---
version: "3.7"
services:
  db:
    image: postgres:${POSTGRES_IMAGE_TAG:-12}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"
      # mount db creation script in place for bootstrap
      - "./config/db:/docker-entrypoint-initdb.d"
    networks:
      - internal

  fhir:
    image: hapiproject/hapi:${FHIR_IMAGE_TAG:-v7.2.0}
    environment:
      management.endpoints.web.exposure.include: "health,prometheus,env,configprops"
      
      SPRING_CONFIG_LOCATION: file:///opt/application.yaml
      spring.datasource.url: jdbc:postgresql://db:5432/hapifhir
      spring.datasource.username: postgres
      spring.datasource.password: postgres
      spring.datasource.driverClassName: org.postgresql.Driver
      spring.jpa.properties.hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect

      # enable IPS; use latest version
      hapi.fhir.ips_enabled: "true"
      hapi.fhir.implementationguides.ips_2_0_0.packageUrl: https://build.fhir.org/ig/HL7/fhir-ips/package.tgz
      hapi.fhir.implementationguides.ips_2_0_0.name: hl7.fhir.uv.ips
      hapi.fhir.implementationguides.ips_2_0_0.version: 2.0.0
      hapi.fhir.server_address: https://fhir.${BASE_DOMAIN:-localtest.me}/fhir/

      # Demo: relax reference and ID requirements for sandbox/testing data sources
      hapi.fhir.allow_external_references: "true"
      hapi.fhir.enforce_referential_integrity_on_write: "false"
      hapi.fhir.auto_create_placeholder_reference_targets: "true"
      hapi.fhir.client_id_strategy: ANY
    # expose HAPI to internet - remove entire `labels` section if unwanted
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fhir-${COMPOSE_PROJECT_NAME}.rule=Host(`fhir.${BASE_DOMAIN:-localtest.me}`)"
      - "traefik.http.routers.fhir-${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.fhir-${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.fhir-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt"
      
       # add CORS middleware, configured to return `Access-Control-Allow-Origin: *`
      # NB accessControlAllowOrigin is deprecated, but not noted in docs
      # https://github.com/traefik/traefik/issues/8796
      - "traefik.http.middlewares.fhir-${COMPOSE_PROJECT_NAME}-cors.headers.accessControlAllowOriginList=*"
      # allow all verbs used by FHIR REST
      - "traefik.http.middlewares.fhir-${COMPOSE_PROJECT_NAME}-cors.headers.accessControlAllowMethods=HEAD,GET,OPTIONS,PATCH,POST,PUT,DELETE"
      - "traefik.http.middlewares.fhir-${COMPOSE_PROJECT_NAME}-cors.headers.accessControlAllowHeaders=Authorization,Origin,Content-Type,Accept"
      - "traefik.http.routers.fhir-${COMPOSE_PROJECT_NAME}.middlewares=fhir-${COMPOSE_PROJECT_NAME}-cors"

      # Hapi does not EXPOSE the ports it listens on, requiring explicit traefik configuration
      - "traefik.http.services.fhir-${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080"
    volumes:
      - "./config/hapi/application.yaml:/opt/application.yaml:ro"
    depends_on:
      - db
    networks:
      ingress:
      internal:
        aliases:
          - fhir-internal

  shl-creator:
    #image: ghcr.io/uwcirg/shl-ips:${SHL_CREATOR_IMAGE_TAG:-latest}
    #image: ghcr.io/uwcirg/shl-ips:${SHL_CREATOR_IMAGE_TAG:-ai-chat-experimental}
    #image: ghcr.io/uwcirg/shl-ips:${SHL_CREATOR_IMAGE_TAG:-epic-uwmed-prod}
    image: ghcr.io/uwcirg/shl-ips:${SHL_CREATOR_IMAGE_TAG:-llm-chat-take-2}
    environment:
      VITE_API_BASE: https://shl-server.${BASE_DOMAIN}/api
      VITE_INTERMEDIATE_FHIR_SERVER_BASE: https://fhir.${BASE_DOMAIN}/fhir/
      VITE_BACK_URL: https://${BASE_DOMAIN}/pro_reports/clinic_report_inform
      VITE_SOF_ISS: https://fhir-auth.${BASE_DOMAIN}/fhir
      VITE_OIDC_SERVER_BASE: https://keycloak.${BASE_DOMAIN}
      VITE_OIDC_LOGOUT_ENDPOINT: https://keycloak.${BASE_DOMAIN}/realms/ltt/protocol/openid-connect/logout
      VITE_OIDC_CHECK_SESSION_IFRAME: https://keycloak.${BASE_DOMAIN}/realms/ltt/protocol/openid-connect/login-status-iframe.html
      VITE_POST_LOGOUT_REDIRECT_URI: https://${BASE_DOMAIN}/users
    env_file:
      shl-creator.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.shl-creator-${COMPOSE_PROJECT_NAME}.rule=Host(`shl-creator.${BASE_DOMAIN}`)
      - traefik.http.routers.shl-creator-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.shl-creator-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.shl-creator-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt
    networks:
      - ingress

  shl-server:
    image: ghcr.io/uwcirg/smart.health.links-server:${SHL_SERVER_IMAGE_TAG:-latest}
    environment:
      PUBLIC_URL: https://shl-server.${BASE_DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.shl-server-${COMPOSE_PROJECT_NAME}.rule=Host(`shl-server.${BASE_DOMAIN}`)
      - traefik.http.routers.shl-server-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.shl-server-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.shl-server-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt
    volumes:
      - shl-server-data:/app/db
    networks:
      - ingress

  llm-service:
    image: ghcr.io/uwcirg/llm-wrap:${LLM_SERVICE_IMAGE_TAG:-latest}
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    #ports:
    #  - "5000:5000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.shl-creator-${COMPOSE_PROJECT_NAME}.rule=Host(`llm-service.${BASE_DOMAIN}`)
      - traefik.http.routers.shl-creator-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.shl-creator-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.shl-creator-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt
    networks:
      - ingress

volumes:
  db-data: {}
  shl-server-data: {}


networks:
  # internal network for backing services
  internal:

  # ingress network
  ingress:
    external: true
    name: external_web
